### ISSUE TITLE
--dedupe not working

### ISSUE THREAD

**Issue by lissertations** [hughrun/pocketsnack#38]
Running `pocketsnack --dedupe --all` isn't working; when the program asks me to enter 'delete' and I do, I get an error. I also tried entering "delete" with quote marks and got a '✋ deletion cancelled' response. 

![image](https://user-images.githubusercontent.com/22556371/103754629-b5ac9100-5060-11eb-9c4b-ddf63f01a2a3.png)

**Comment by hughrun** [comment]
Thanks @lissertations - this seems to be caused by Pocket returning a `403` response instead of a `200`. I'm a bit perplexed by why, because that wasn't happening previously, but I can replicate it so it's not just you. I'm investigating.

**Comment by hughrun** [comment]
update: still waiting for Pocket support to get back to me on this. I pinged them again today.

**Comment by hughrun** [comment]
@lissertations this turned out to be a stupid coding bug 😣.

Please try uninstalling, and then install the pre-release from PyPi:
```
pip install pocketsnack==3.1.0a0
```
If you can confirm this fixes the errors you were seeing, and doesn't seem to create any new ones, I'll release it as a full version.
